import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar/NavBar";
import { Box } from "@mui/material";
import { getUserInfo } from "@/lib/auth/actions";
import { UserProvider } from "@/components/providers/UserProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUserInfo();

  return (
    <html lang="en">
      <body>
        <UserProvider value={user}r>
          <Box sx={{ background: "linear-gradient(180deg, #2C1D68, #5638CE)" }}>
            <NavBar />
            {children}
          </Box>
        </UserProvider>
      </body>
    </html>
  );
}
