name: Formatting, Testing, Building

on:
  pull_request:
    types:
      - labeled

jobs:
  build:
    if: ${{ github.event.label.name == 'build' }}
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install Dependencies
        run: npm ci

      - name: Formatting
        run: npm run format-check

      - name: Testing
        run: echo 'Testing...'

      - name: Building
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: "https://fake-url.supabase.co"
          NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: "fake-anon-key"
          SUPABASE_SERVICE_ROLE_KEY: "fake-service-role-key"
          NODE_ENV: "production"
